all:
	pdflatex informe.tex
	pdflatex informe.tex

run: all
	okular informe.pdf
	
clean:
	rm -f *.pdf
	rm -f *.aux
	rm -f *.toc
	rm -f *.log
	rm -f *.idx
	rm -f *.backup
	rm -f *.out
	rm -f *.ind
	rm -f *.ilg
